kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-accelstor
spec:
  selector:
    matchLabels:
      app: csi-accelstor
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-accelstor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-accelstor
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        "kubernetes.io/os": linux
      hostNetwork: true
      serviceAccount: csi-accelstor
      initContainers:
        - name: init-csi
          image: quay.io/accelstor/accelcsi:latest
          command: ["/bin/rm", "-rf", "/csi/csi.sock"]
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v2.0.2
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v4.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.0.1
          args:
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
          - mountPath: /registration
            name: registration-dir
        - name: iscsid
          image: quay.io/accelstor/accelcsi:latest
          command: ["/sbin/iscsid", "-f"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: modules
              mountPath: /lib/modules
            - name: run
              mountPath: /run
            - name: dev
              mountPath: /dev
        - name: accelcsi
          image: quay.io/accelstor/accelcsi:latest
          args:
            - "-ip=$(AFA_IP)"
            - "-key=$(AFA_KEY)"
            - "-https=$(AFA_HTTPS)"
            - "-nodeid=$(KUBE_NODE_NAME),$(KUBE_POD_IP)"
          env:
            - name: AFA_IP
              value: "10.146.6.103"
            - name: AFA_KEY
              value: "47b333580f8cba0662835c149492887e12580735"
            - name: AFA_HTTPS
              value: "false"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: pods
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: modules
              mountPath: /lib/modules
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /run
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.accelstor.com
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: pods
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: dev
          hostPath:
            path: /dev
        - name: run
          hostPath:
            path: /run
