kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-controller-accelstor
spec:
  selector:
    matchLabels:
      app: csi-controller-accelstor
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-controller-accelstor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      nodeSelector:
        "kubernetes.io/os": linux
      hostNetwork: true
      serviceAccount: csi-accelstor
      initContainers:
        - name: init-csi
          image: quay.io/accelstor/accelcsi:v4.0.7r2
          command: ["/bin/sh", "-c"]
          args:
            - /bin/mkdir -P /var/lib/kubelet/plugins/csi.accelstor.com;
              /bin/rm -rf /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v2.0.2
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.1.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
        - name: csi-snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v4.0.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=false"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
        - name: csi-resizer
          image: gcr.io/k8s-staging-sig-storage/csi-resizer:canary
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=false"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
        - name: accelcsi
          image: quay.io/accelstor/accelcsi:v4.0.7r2
          args:
            - "-ip=$(AFA_IP)"
            #- "-ip2=$(AFA_IP2)" #Only set in H series
            #- "-virtualip=$(AFA_VIRTUALIP)"  #Set if you wanna use NFS with dataport
            - "-key=$(AFA_KEY)"
            - "-https=$(AFA_HTTPS)"
            - "-nodeid=$(KUBE_NODE_NAME),$(KUBE_POD_IP)"
            - "-csi-address=$(ADDRESS)"
            #- "-csi-name=$(CSI_DRIVE_NAME)" #Set if you wanna use different driveName
          env:
            - name: AFA_IP
              value: "10.146.6.104"
            - name: AFA_IP2
              value: "10.146.6.105" #Only set in H series
            - name: AFA_VIRTUALIP
              value: "10.146.6.105" #Set if you wanna use NFS with dataport
            - name: AFA_KEY
              value: "c892ce6663c0779fb6883c0b7e111b9deed1b6c4"
            - name: AFA_HTTPS
              value: "false"
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.accelstor.com/csi.sock
            - name: CSI_DRIVE_NAME
              value: "csi.accelstor.com"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
              mountPropagation: "Bidirectional"
            - name: modules
              mountPath: /lib/modules
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /run
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: var-lib
          hostPath:
            path: /var/lib/
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: dev
          hostPath:
            path: /dev
        - name: run
          hostPath:
            path: /run
        - name: localtime
          hostPath:
            path: /etc/localtime

---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-accelstor-node
spec:
  selector:
    matchLabels:
      app: csi-accelstor-node
  template:
    metadata:
      labels:
        app: csi-accelstor-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-accelstor
            topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        "kubernetes.io/os": linux
      hostNetwork: true
      serviceAccount: csi-accelstor
      initContainers:
        - name: init-csi
          image: quay.io/accelstor/accelcsi:v4.0.7r2
          command: ["/bin/sh", "-c"]
          args:
            - /bin/mkdir -P /var/lib/kubelet/plugins/csi-node.accelstor.com;
              /bin/rm -rf /var/lib/kubelet/plugins/csi-node.accelstor.com/csi.sock
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
      containers:
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.0.1
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(ADDRESS)
          imagePullPolicy: IfNotPresent
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-node.accelstor.com/csi.sock
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
            - mountPath: /registration
              name: registration-dir
        - name: accelcsi
          image: quay.io/accelstor/accelcsi:v4.0.7r2
          args:
            - "-ip=$(AFA_IP)"
            #- "-ip2=$(AFA_IP2)" #Only set in H series
            #- "-virtualip=$(AFA_VIRTUALIP)"  #Set if you wanna use NFS with dataport
            - "-key=$(AFA_KEY)"
            - "-https=$(AFA_HTTPS)"
            - "-nodeid=$(KUBE_NODE_NAME),$(KUBE_POD_IP)"
            - "-csi-address=$(ADDRESS)"
            #- "-csi-name=$(CSI_DRIVE_NAME)" #Set if you wanna use different driveName
          env:
            - name: AFA_IP
              value: "10.146.6.104"
            - name: AFA_IP2
              value: "10.146.6.105" #Only set in H series
            - name: AFA_VIRTUALIP
              value: "10.146.6.105" #Set if you wanna use NFS with dataport
            - name: AFA_KEY
              value: "c892ce6663c0779fb6883c0b7e111b9deed1b6c4"
            - name: AFA_HTTPS
              value: "false"
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-node.accelstor.com/csi.sock
            - name: CSI_DRIVE_NAME
              value: "csi.accelstor.com"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: var-lib
              mountPath: /var/lib/
              mountPropagation: "Bidirectional"
            - name: modules
              mountPath: /lib/modules
            - name: dev
              mountPath: /dev
            - name: run
              mountPath: /run
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true

            - name: iscsiadm
              mountPath: /host/usr/sbin/iscsiadm
            - name: lib64
              mountPath: /host/lib64
            - name: iscsi-run-lock
              mountPath: /host/run/lock/iscsi
            - name: iscsi-var-lock
              mountPath: /host/var/lock/iscsi
            - name: iscsi-lib
              mountPath: /host/var/lib/iscsi
            - name: iscsi-config
              mountPath: /host/etc/iscsi/
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: var-lib
          hostPath:
            path: /var/lib/
            type: Directory
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: dev
          hostPath:
            path: /dev
        - name: run
          hostPath:
            path: /run
        - name: localtime
          hostPath:
            path: /etc/localtime

        - name: iscsiadm
          hostPath:
            path: /usr/sbin/iscsiadm
            type: File
        - name: lib64
          hostPath:
            path: /lib64
            type: Directory
        - name: iscsi-run-lock
          hostPath:
            path: /run/lock/iscsi
        - name: iscsi-var-lock
          hostPath:
            path: /var/lock/iscsi
        - name: iscsi-lib
          hostPath:
            path: /var/lib/iscsi
        - name: iscsi-config
          hostPath:
            path: /etc/iscsi/
