apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-accelstor
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-attacher-role
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-attacher-runner # from rbac-external-attacher.yaml
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-snapshotter-role
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-snapshotter-runner # from rbac-external-attacher.yaml
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-attacher-role-cfg
  namespace: default
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: Role
  name: external-attacher-cfg # from rbac-external-attacher.yaml
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-snapshotter-role-cfg
  namespace: default
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: Role
  name: external-snapshotter-cfg # from rbac-external-attacher.yaml
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-provisioner-role
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: ClusterRole
  name: external-provisioner-runner # from rbac-external-provisioner.yaml
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-accelstor-provisioner-role-cfg
  namespace: default
subjects:
  - kind: ServiceAccount
    name: csi-accelstor
    namespace: default
roleRef:
  kind: Role
  name: external-provisioner-cfg # from rbac-external-provisioner.yaml
  apiGroup: rbac.authorization.k8s.io
