apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs.csi.accelstor.com
provisioner: csi.accelstor.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  type: nfs
